# docker-compose configuration file
version: '3.7'
services:
  relational_database:
    env_file: ./.env
    image: 'postgres'
    container_name: 'relational_database'
# Conf for complex architectures
#    expose:
#      - '${DB_PORT}'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ../sql:/var/lib/postgresql/data/
  norelational_database:
    env_file: ./.env
    image: 'mongo'
    container_name: 'norelational_database'
    ports:
      - '${NDB_PORT}:${NDB_PORT}'
    volumes:
      - ../nosql:/data/db
